### ISSUE TITLE
Page layout has error on the Chrome

### ISSUE THREAD

**Issue by Yogayu** [madebyconnor/summer#3]
Hi, Connor Bär:

I love your summer theme. I use it as [my wiki page's theme](http://azureyu.com/wiki), but the page layout has error on the Chrome. Do you have any idea?

![wiki_ _azureyu](https://user-images.githubusercontent.com/10155763/28764220-901e0164-75f6-11e7-9c61-fd2bd3fa6045.png)

Thanks!

**Comment by connor-baer** [comment]
Hi @Yogayu,

which version of Chrome do you use? Works perfectly for me (Chrome 55-60): 

![screenshot 2017-07-31 09 12 47](https://user-images.githubusercontent.com/11017722/28766635-c162f868-75d0-11e7-9e4b-6d6d5e523289.png)

**Comment by Yogayu** [comment]
My Chrome Version is 59.0.3071.115 (64 bit). 
After updating the Chrome to 60.0.3112.78 (64 bit) , it looks fine now. 
Thanks again~ !
@connor-baer
